stages:
  - build
  - test

build:
  stage: build
  script:
    - xcodebuild clean build -project ProfitTracker.xcodeproj -scheme ProfitTracker

test:
  stage: test
  script:
    - xcodebuild test -project ProfitTracker.xcodeproj -scheme ProfitTrackerTests -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.4' -testLanguage pt-BR
    - xcodebuild test -project ProfitTracker.xcodeproj -scheme ProfitTrackerTests -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.4' -testLanguage en

