name: build-and-test
on: [push]
jobs:
  build-project:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild clean build -project ProfitTracker.xcodeproj -scheme ProfitTracker
  test-project:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild test -project ProfitTracker.xcodeproj -scheme ProfitTrackerTests -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.4' -testLanguage pt_BR
      - run: xcodebuild test -project ProfitTracker.xcodeproj -scheme ProfitTrackerTests -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.4' -testLanguage en
